---
kind: pipeline
name: ebpf-autoinstrument
steps:
- image: thegeeklab/drone-docker-buildx:23
  name: ebpf-autoinstrument-dryrun-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/ebpf-autoinstrument-dryrun
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request
- image: thegeeklab/drone-docker-buildx:23
  name: ebpf-autoinstrument-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    dry_run: false
    password:
      from_secret: docker_password
    platforms:
    - linux/arm64
    - linux/amd64
    repo: grafana/ebpf-autoinstrument
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: signature
hmac: 3ba97e977eb91bed50eba8df4f1043a7fee5b7e857fb17431368e075876f5210

...
