name: Lint prose with Vale
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: grafana/vale:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linter
        run: >
          /bin/reviewdog
          --conf=/etc/vale/.reviewdog.yml
          --fail-on-error
          --reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
